### ISSUE TITLE
Error in run_reddit.py

### ISSUE THREAD

**Issue by xz-keg** [huangwb/AS-GCN#3]
Traceback (most recent call last):
  File "run_reddit.py", line 207, in <module>
    main(FLAGS.rank,FLAGS.rank)
  File "run_reddit.py", line 183, in main
    cost, acc, duration = increment_evaluate(features, adj, test_index, y_test, [], placeholders)
  File "run_reddit.py", line 116, in increment_evaluate
    for batch_start in xrange(0, num_nodes, batchsize):
NameError: name 'xrange' is not defined

**Comment by xz-keg** [comment]
After fixing the above bug by modifying xrange(* to range(*   , the following bug appears

tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[{{node _arg_Placeholder_8_0_7}}]]
	 [[node add_6 (defined at models.py:286) ]]

**Comment by xz-keg** [comment]
I fixed all those bugs and finally run the code.

However, multiple times of run results in around 0.944 on reddit dataset, instead of 0.963 in paper.

I'd like to ask if I which hyperparemeters shall be modified to get the result in paper.

**Comment by xuesanshi** [comment]
are you try to run the load_data_original in utils.py?

**Comment by xz-keg** [comment]
> are you try to run the load_data_original in utils.py?

No I haven't. I guess you cannot run it since there are also many bugs in their model and layer code besides  load_data.
