### ISSUE TITLE
about the load_data_original in the utils.py

### ISSUE THREAD

**Issue by xuesanshi** [huangwb/AS-GCN#4]
When I tried to run the raw data, I found that the result of running was always 0.093. Can your model run on the original data?think you

**Comment by xuesanshi** [comment]
and when i run the load_data_original,there are some questions 
 File "F:/AS-GCN-master/run_pubmed.py", line 166, in main
    print("Epoch:", '%04d' % (epoch + 1), "train_loss=", "{:.5f}".format(outs[1]),
UnboundLocalError: local variable 'outs' referenced before assignment

**Comment by huangwb** [comment]
I did not test anything about the function load_data_original. There are something different around load_data compared with load_data_original.
