### ISSUE TITLE
Training time per epoch on Full GCN

### ISSUE THREAD

**Issue by Yihan-zz** [huangwb/AS-GCN#9]
Thanks for your great works !
I didthe experiments on the GCN provided on [here](https://github.com/tkipf/pygcn) and record the training time per epoch and the results on Pubmed is about 0.008s/epoch, but the result on your paper is about 100s/epoch. Can your provide your Full GCN code or do I miss something?

**Comment by huangwb** [comment]
Hi, thanks for you interest. Original GCN is under the the full-batch setting, where one epoch computes one full batch of graph. In our paper and also fastGCN, we assume when dealing with large-scale graphs (although pubmed is not big enough to meet this assumption), the machine memory can not fit the whole graph at a time, thus a mini-batch training is adopted, which means one epoch consists of many batches of training. For fair comparison, all baselines in our paper employed the mini-batch training fashion. To implement full GCN in our code source, you can modify the sampler.py file by reloading the samlying with full neighbor returnning.

**Comment by Yihan-zz** [comment]
thanks
